spring:
  application:
    name: Icy

  datasource:
    url: ${URL}
    username: ${NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: ${SECRET}